### ISSUE TITLE
Generalized master-stack layout engine

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#634]
Create a generalized master-stack layout engine, defined in terms of `N` columns, where all but one column has a maximum number of rows.

For example:

- `2 * 1 * X` would be a 3-column layout, where:
  - the first column has two rows
  - the second has one row
  - all remaining windows are stacked in the third row.
- `1 * X` for a classic master stack layout.
- `2 * X` for a master stack with two master windows.

**Comment by urob** [comment]
A few suggestions for commands to be exposed with this plugin.

## Preliminaries

### Windows order

Some of the commands below require a *order* of windows. I suggest ordering windows column-wise. This seems a reasonable extension of what most people would expect on a traditional `1 * X` stack. That is,
```
(c1, r1) -> (c1, r2) -> ... -> (c2, r1) -> (c2, r2) -> ... 
```

### Master column

While the core of this layout engine does not require defining a `master column`, I think that it makes sense to expose some commands that use the concept of a `master column` (see below). 

On the one hand, this is what people expect from a master-stack layout. On the other hand, this simplifies the logic of exposing certain functionalities. E.g., an alternative to the `promote_*` commands suggested below, would be to offer more flexible commands that allow to focus/move windows to *any* column/row. But personally, I see limited use of doing this in addition to other existing/suggested commands, and the implementation seems to be much more messy.

To keep things simple, I suggest using a `master_column` instead of a `master_area` b/c it generalizes nicely when there are more than 1 master-rows without over-complicating things. Which column is considered the `master_column` would be defined in the initial setup of the layout.

I.e., a complete `layout definition` would consist of:
- a *tuple of max-rows, which also implicitly defines the number of columns. E.g., `(2, -1, 2)` defines a 3-column layout where the first and last column have a maximum of 2 rows each, and where all additional windows go to the middle column (indicated by the `-1` here)
- a *scalar* that indicates the column number of the "master-column; e.g., `3` for the last column in the example above.

## Commands

- `focus_[next|previous]_window`: cycles the focus using the ordering from above
- `swap_with_[next|previous]_window`: swaps window with next/previous window.
- `promote_focus`: focus the *first row* of the master column
- `promote_window`: swaps window with the window in the first row of the master column and focus that window
- `[increment|decrement]_master_width`: resize width of master column. If there are columns to either side of the master column, then this would equally shift the edges on both sides.

## Open question

### `promote_window`: swap or rotate?

I wasn't sure whether promoting a window to the first row of the master area should only swap the two affected windows, or whether it should trigger a rotation down the stack of all in-between windows? 

I think the decision really comes down to where the old master window should go. Should it swap positions with the new master window, or should it move down the stack (e.g., with >1 master rows, it would move to row2 in the master column). It would be interesting to hear what other think about that.

### Order in which positions get populated by new windows

This matters whenever the current window number is less than the number of max-rows in all columns other than the "catch-all" column. I suspect that preferences differ on this.

My suggestion would be to initially go with a `column-first` order, where new window are created in the `window order` defined above. This definitely seems easiest and I think is reasonable. If there is demand, other creation-orders could be possibly added later on (though I wonder, it in this case, it would be easier to also change the window order). 

## Interaction with other feature requests

### Move_and_focus (#662)

Personally, I don't see much use of a `promote_window` command that doesn't focus the new master-window after. So I would just make that the default.

For the `swap_with_[next|previous]_window` commands it would probably make sense to expose both `swap_*` and `swap_and_focus_*` versions.

**Comment by gplusplus314** [comment]
I have some thoughts.

Proposed MVP:
- Put windows in a List data structure.
- Given a List of windows, arrange them on the screen.

^^ That's it. Once that works, we can expand more easily, IMO.

Quick terminology/concepts that I think can simplify this:
- An *Area* can be either a row or a column (example: rotating screen orientation, you probably want rows)
- An Area can nest another Area (more on that later)
- An Area is responsible for the layout/arrangement of a *capacity* of windows in the List structure and this can be configurable. For example, the Primary area (colloquially "master") would likely default to 1, whereas an Overflow area (colloquially "stack") would likely default to infinity (or some sane large number).
- By convention, the Primary area is the one responsible for arranging the window with the lowest index in the List up to its configured capacity, which can be zero (perfectly valid). Each additional Area (non-Primary) continues the layout up to its configured capacity.

I believe the implementation gets vastly simplified if its thought about in these terms. This allows us to make no assumptions of people's screen resolutions, screen orientation, use cases, or layout preferences. This also generalizes well to other automatic tiling layouts such as Fibonacci, Dwindle, etc, by nesting Areas programmatically. We can provide sane defaults that most people would expect, such as a DWM-style 2-column.

As far as operations with this model, things like rotating and transposing become independent of being a row or a column. Areas could also be laid out independently, such as having the Primary as the middle column of a 3-column (that is, three-Area) arrangement.

The key is to use an ordered, linear collection (List or equivalent) and map an Area to a range on that list. As windows enter and exit the workspace, they would be either appended or prepended to the list (configurable) and then the MVP code described in the beginning of my rant would take over.

Another thing to consider is the social responsibility of the chosen terminology. GitHub now uses "main" as the default branch name, for example.

**Comment by dalyIsaac** [comment]
Ok. I was looking through this today to get a handle on it. This is my basic understanding of a layout engine which would handle most cases:

### Probable MVP

- `List` data structure
- An `Area` is a row or a column
- An `Area` can contain windows and child `Area`s
- An `Area` is one of the following variants:
	- `LeaderArea` (or primary/main), which has priority $P$ and max-count $N$
	- `StackArea` with infinite max-count, which has priority $S$
	- `LeafArea` to allow child `Area`s to exist not at the start, with max-count $L$ and priority from the parent `Area`
- `LeaderArea` priorities > `StackArea` priorities
- A window can be "swapped" or "rotated" to the nearest `LeaderArea`, or the next `LeaderArea` with a higher priority $P$
- Defaults will be provided by the plugin to select from
- Custom layouts can be created by:

```csharp
LeaderArea(
	direction: row,
	LeaderArea(leaderPriority: 0, max: 1),
	LeaderArea(leaderPriority: 1, max: 3, direction: column),
	StackArea(
		stackPriority: 0,
		LeafArea(2),
		LeaderArea(leaderPriority: 2, direction: column),
		LeafArea(Infinite)
	)
)
```

### Follow-on tickets

- A child `Area` can take some % of the parent `Area`
- Reverse direction (reverse column, reverse row)
- Updating of the data structure during runtime via commands
- Window in direction operations

**Comment by dalyIsaac** [comment]
## Progress

- [x] Create project
- [x] Fles out `IArea` models
- [x] Implement `AddWindow` and `RemoveWindow`
- [x] Implement `DoLayout` and `MoveWindowToPoint`
- [x] `CreatePrimaryStackLayout`
- [x] `CrateMultiColumnLayout`
- [x] `FocusWindowInDirection`
- [x] `SwapWindowInDirection`
- [x] Set insertion type command
- [ ] Promote/demote window command
- [ ] Test custom layouts
  - [ ] Nested `ParentArea`
  - [ ] Column `ParentArea`
  - [ ] `OverflowArea` not being on the right
  - [ ] `OverflowArea` being omitted
- [ ] TODOs
- [ ] Tests

## Follow-up issues

- [ ] Move window edges in direction (just parent vs. all windows)
- [ ] Reverse direction
- [ ] Bar component for insertion type
