### ISSUE TITLE
Investigate `FocusIndicator` flickering

### ISSUE THREAD

**Issue by dalyIsaac** [dalyIsaac/Whim#918]

**Comment by urob** [comment]
Adding a screencast and some logs:

https://github.com/dalyIsaac/Whim/assets/978080/427d80b5-a69d-4711-840f-25b523821c10

The logs below start right after I changed to `workspace 1` on my primary monitor (`DISPLAY`). For the entire duration, `workspace 2` was active (but unfocused) on my other monitor (`DISPLAY1`). Interestingly, even though `workspace 2` was never focused, the logs are full of events about `workspace 2`.

~I apologize for the logs being enormous. I wanted to include the entire history since focusing `workspace 1`. But if you focus on just the last few seconds from, say, `10:23:45:000` to the end `10:23:51.604` there were plenty of flickering events throughout that window.~

EDIT: The file was just too massive, so I truncated it to the last 8 seconds. Let me know if there's anything else that would be useful.

[flicker.log](https://github.com/user-attachments/files/16015906/flicker.log)

**Comment by urob** [comment]
Let me add that this also occurs with the default config. It usually takes a few minutes to start and seems to require windows open on multiple workspaces/monitors (I haven't pinned down the exact conditions). But once it starts, it stays (always affecting the currently focused window regardless on which workspace/monitor) and even seems to get progressively worse to the point where the border disappears for most of the time and only occasionally flickers back on.

**Comment by urob** [comment]
One more observation:

Keeping things running for a while, it seems that the flicker (or whatever causes it) ended up freezing whim eventually. That is, it would no longer respond to keybinds or interacting with the status bar via the mouse.

**Comment by dalyIsaac** [comment]
I've resolved the flickering - that was a nice simple fix. I'll fix the logs being too verbose later. I think I've seen that freeze - my hunch is that it's separate to this, I'm keeping an eye out for it.
